apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: orders-db
  name: orders-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cinder-csi
  volumeMode: Filesystem
