apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sock-shop-privileged
  namespace: sock-shop
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sock-shop-privileged
  namespace: sock-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sock-shop-privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: sock-shop